module.exports = {
    "boost": ["Boosting engines."],
	"youThere": ["I'm here and ready to help."],
	"balencePower": ["Balancing power."],
	"cancelDocking": ["Cancelling docking request."],
	"cargoScan": ["Scanning cargo."],
	"deployChaff": ["Deploying chaff."],
	"deployHardpoints": ["Deploying weapons."],
	"deployLandingGear": ["Deploying landing gear."],
	"deployCargoScoop": ["Deploying cargo scoop."],
	"deploySRV": ["Deploying SRV."],
	"exitFrameShift": ["Exiting frame shift drive."],
	"exitCruise": ["Exiting super cruise."],
	"powerToEngines": ["Diverting power to engines."],
	"powerToSystems": ["Diverting power to systems."],
	"powerToWeapons": ["Diverting power to weapons."],
	"emergencyStop": ["initializing emergency stop."],
	"engageFrameShift": ["Engaging frameshift drive."],
	"engageCruise": ["Engaging supercruise."],
	"flightAssistOff": ["Turning fight assist off."],
	"flightAssistOn": ["Turning flight assist on."],
	"Screenshot": ["Taking screenshot."],
	"targetEnemy": ["Targeting enemy."],
	"launch": ["Preparing to launch."],
	"lightsOn": ["Turning lights on."],
	"lightsOff": ["Turning lights off."],
	"enginesForwardOneHundredPercent": ["Engines one hundred percent."],
	"enginesForwardNintyPercent": ["Engines ninty percent."],
	"enginesForwardEightyPercent": ["Engines eighty percent."],
	"enginesForwardSeventyFivePercent": ["Engines seventy five percent."],
	"enginesForwardSeventyPercent": ["Engines seventy percent."],
	"enginesForwardSixtyPercent": ["Engines sixty percent."],
	"enginesForwardFiftyPercent": ["Engines fifty percent."],
	"enginesForwardFortyPercent": ["Engines forty percent."],
	"enginesForwardThirtyPercent": ["Engines thrity percent."],
	"enginesForwardTwentyFivePercent": ["Engines twenty five percent."],
	"enginesForwardTwentyPercent": ["Engines twenty percent."],
	"enginesForwardTenPercent": ["Engines ten percent."],
	"nextFireGroup": ["Selecting next fire group."],
	"nextHostile": ["Targeting next hostile."],
	"nextSystem": ["Selecting next star system."],
	"nextShip": ["Selecting next ship."],
	"prevFireGroup": ["Changing to previous fire group."],
	"prevHostile": ["Targeting previous hostile."],
	"prevShip": ["Selecting previous ship."],
	"dockingRequest": ["Requesting docking."],
	"diognostics": ["All good"],
	"centerHeadset": ["Centering headset."],
	"retractHardpoints": ["Retracting hardpoints."],
	"retractLandingGear": ["Retracting landing gear."],
	"retractCargoScoop": ["Retracting cargo scoop."],
	"enginesBackwardOneHundredPercent": ["Setting engines to one hundred percent backward."],
	"enginesBackwardSeventyFivePercent": ["Setting engines to seventy five percent backward."],
	"enginesBackwardFiftyPercent": ["Setting engines to fifty percent backward."],
	"enginesBackwardTwentyFivePercent": ["Setting engines to twenty five percent backward."],
	"SRVRecovery": ["Recovering SRV."],
	"stopEngines": ["Cutting engines."],
	"whatsNext": [" Whats next?"],
	"thankYou": ["You're welcome."],
	"thatsAll": ["Okay."],
	"unknownIntent": ["I don't know what you said."]
};






